export const token =
  "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwb3NpdGlvbklkIjoiMGY5ZDZhOGUtZTM3NC00ODAzLTg4MzctYjgxM2JhODMxMzE4IiwicHJvamVjdElkIjoiM2I0ZDk2MDEtMDg3OS00ZWQzLTk1MjctYTRlNDliMjcxNWEwIiwiZnVsbE5hbWUiOiJTYW11ZWwgUGFpeiIsImVtYWlsIjoiZ2VvdmFubnlfcGFpekBob3RtYWlsLmNvbSIsImlhdCI6MTcyNzcwNDU4N30.wvgZHYjWeMb7JfwZnYmZj8K3KxHekqx3VFNwAa1B-qk";
